# Config for GCP deployment
runtime: custom
env: flex
includes:
  - env_variables.yaml
resources:
  cpu: 1
  memory_gb: 2.0
  disk_size_gb: 10
network:
  session_affinity: true
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 8
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.8